Investing in the U.S. stock market offers a plethora of opportunities across various sectors. Below is a curated list of 20 stocks, each priced under $50, spanning diverse industries. For each stock, we've provided the current price in both USD and INR (using an exchange rate of 1 USD = 82.50 INR), the sector, key considerations, and projected price targets for 2025, 2029, and 2030.

| Stock Name                 | Current Price (USD) | Current Price (INR) | Sector                 | Remarks / Why Consider?                                                                                                                                                                                                                 | 2025 Target (USD) | 2025 Target (INR) | 2029 Target (USD) | 2029 Target (INR) | 2030 Target (USD) | 2030 Target (INR) |
|----------------------------|---------------------|---------------------|------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------|-------------------|-------------------|-------------------|-------------------|-------------------|
| **UiPath Inc.**            | $14.29              | ₹1,179              | Technology             | Leading in robotic process automation (RPA) with significant growth potential as businesses increasingly adopt automation solutions.                                                                                                   | $20               | ₹1,650            | $30               | ₹2,475            | $35               | ₹2,888            |
| **Northern Oil and Gas**   | $35.61              | ₹2,939              | Energy                 | Focused on non-operated interests in oil and gas properties, benefiting from strategic acquisitions and potential oil price recovery.                                                                                                   | $45               | ₹3,713            | $55               | ₹4,538            | $60               | ₹4,950            |
| **ExlService Holdings**    | $51.80              | ₹4,279              | Business Services      | Provides analytics and digital solutions, well-positioned to capitalize on the growing demand for data-driven decision-making in various industries.                                                                                     | $65               | ₹5,363            | $80               | ₹6,600            | $90               | ₹7,425            |
| **Avanos Medical Inc.**    | $16.99              | ₹1,402              | Healthcare             | Specializes in medical devices, with a focus on pain management and chronic care solutions, addressing critical needs in the healthcare sector.                                                                                         | $25               | ₹2,063            | $35               | ₹2,888            | $40               | ₹3,300            |
| **Universal Technical Inst.| $29.53              | ₹2,435              | Education              | Provides technical education training, catering to the increasing demand for skilled labor in various industries, including automotive and marine sectors.                                                                               | $40               | ₹3,300            | $55               | ₹4,538            | $60               | ₹4,950            |
| **Coupang Inc.**           | $23.86              | ₹1,969              | E-commerce             | South Korea's leading e-commerce platform, known for its rapid delivery services and expanding market share in the Asian e-commerce landscape.                                                                                           | $35               | ₹2,888            | $50               | ₹4,125            | $60               | ₹4,950            |
| **Bank of America Corp.**  | $47.74              | ₹3,939              | Financials             | One of the largest financial institutions globally, with diverse services and a strong position to benefit from economic growth and rising interest rates.                                                                               | $60               | ₹4,950            | $75               | ₹6,188            | $85               | ₹7,013            |
| **Teck Resources Ltd.**    | $42.59              | ₹3,514              | Materials              | Diversified mining company with interests in copper, zinc, and coal, poised to benefit from global infrastructure development and commodity demand.                                                                                      | $55               | ₹4,538            | $70               | ₹5,775            | $80               | ₹6,600            |
| **Pfizer Inc.**            | $25.83              | ₹2,132              | Pharmaceuticals        | Global pharmaceutical giant with a robust pipeline, known for its innovations and contributions to global health, including vaccine development.                                                                                        | $35               | ₹2,888            | $45               | ₹3,713            | $50               | ₹4,125            |
| **Globus Maritime Ltd.**   | $1.38               | ₹114                | Shipping               | Engages in the dry bulk shipping industry, with potential upside linked to global trade recovery and favorable shipping rates.                                                                                                           | $3                | ₹248              | $5                | ₹413              | $6                | ₹495              |
| **Diversified Healthcare Trust** | $2.71        | ₹223                | Real Estate            | Focuses on healthcare and life sciences real estate, offering exposure to the growing demand for medical facilities and senior living communities.                                                                                       | $5                | ₹413              | $7                | ₹578              | $8                | ₹660              |
| **Telesat Corp.**          | $19.87              | ₹1,640              | Telecommunications     | Satellite operator with plans to expand broadband services, aiming to capitalize on the increasing demand for global connectivity solutions.                                                                                            | $30               | ₹2,475            | $45               | ₹3,713            | $50               | ₹4,125            |
| **Smart Sand Inc.**        | $2.31               | ₹191                | Energy                 | Provides sand for hydraulic fracturing in the oil and gas industry, with potential growth tied to energy sector recovery and increased drilling activities.                                                                               | $4                | ₹330              | $6                | ₹495              | $7                | ₹578              |
| **Star Equity Holdings Inc.** | $2.14            | ₹177                | Diversified            | Operates in various sectors, including healthcare and construction, offering diversified exposure with potential for value appreciation through strategic initiatives.                                                                   | $4                | ₹330              | $6                | ₹495              | $7                | ₹578              |
| **Xcel Brands Inc.**       | $0.40               | ₹33                 | Consumer Goods         | Engages in consumer products with a focus on brand development and marketing, aiming to leverage consumer trends and brand recognition for growth.                                                                                       | $1                | ₹83               | $2                | ₹165              | $3                | ₹248              |
| **Ebang International Holdings Inc.** | $5.67   | ₹468                | Technology             | Develops cryptocurrency mining hardware, positioned to benefit from the growth of blockchain technology and digital asset adoption.                                                                                                     | $10               | ₹825              | $15               | ₹1,238            | $18               | ₹1,485            |
| **OptimumBank Holdings Inc.** | $4.60            | ₹380                | Financials             | Community bank with potential for growth through local economic development and strategic expansion initiatives.                                                                                                                        | $8                | ₹660              | $12               | ₹990              | $15               | ₹1 